# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rfricg4L6YyUqlmD2z_uLBPXpLTamKJG
"""

from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd
import joblib

# Load trained model
MODEL_PATH = "model.pkl"
model = joblib.load(MODEL_PATH)

FINAL_THRESHOLD = 0.45

app = FastAPI(
    title="Customer Churn Prediction API",
    description="Predict customer churn risk within the next 60 days",
    version="1.0"
)


class CustomerData(BaseModel):
    recency_days: float
    frequency_180d: float
    monetary_180d: float
    return_rate_180d: float
    avg_discount_pct_180d: float
    avg_rating_180d: float
    category_diversity_180d: float

    ticket_count_90d: float
    negative_ticket_rate_90d: float
    avg_resolution_hours_90d: float

    days_since_signup: float

    sessions_30d: float
    product_views_30d: float
    cart_adds_30d: float
    wishlist_adds_30d: float
    abandoned_carts_30d: float

    email_opens_30d: float
    campaign_clicks_30d: float

    last_visit_days_ago: float

    city_tier: str
    age_group: str
    acquisition_channel: str
    loyalty_tier: str
    preferred_category: str
    marketing_consent: str


def generate_risk_explanation(data):
    explanations = []

    if data["recency_days"] > 120:
        explanations.append("long period since last purchase")

    if data["negative_ticket_rate_90d"] > 0.5:
        explanations.append("negative support interactions")

    if data["return_rate_180d"] > 0.20:
        explanations.append("high product return rate")

    if data["avg_discount_pct_180d"] > 0.40:
        explanations.append("heavy discount dependency")

    if data["sessions_30d"] < 3:
        explanations.append("low recent engagement")

    if data["loyalty_tier"] == "Platinum":
        explanations.append("premium loyalty member")

    if len(explanations) == 0:
        return "No major churn risk indicators detected"

    return ", ".join(explanations)


def predict_customer(data):

    df = pd.DataFrame([data])

    probability = model.predict_proba(df)[0][1]

    prediction = int(probability >= FINAL_THRESHOLD)

    if probability >= 0.70:
        risk_level = "High"
    elif probability >= FINAL_THRESHOLD:
        risk_level = "Medium"
    else:
        risk_level = "Low"

    return {
        "churn_probability": round(float(probability), 4),
        "predicted_class": prediction,
        "risk_level": risk_level,
        "risk_explanation": generate_risk_explanation(data)
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }


@app.post("/predict")
def predict(customer: CustomerData):

    result = predict_customer(
        customer.model_dump()
    )

    return result


@app.post("/batch_predict")
def batch_predict(customers: list[CustomerData]):

    results = []

    for customer in customers:
        results.append(
            predict_customer(customer.model_dump())
        )

    return results