# -*- coding: utf-8 -*-
"""test_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p67U3_gStSb1irXlY2DDWP3N8eF7nN-N
"""

from fastapi.testclient import TestClient
from main import app

client = TestClient(app)


def test_health():

    response = client.get("/health")

    assert response.status_code == 200

    assert response.json() == {
        "status": "healthy"
    }


def test_high_risk_customer():

    payload = {
        "recency_days": 250,
        "frequency_180d": 1,
        "monetary_180d": 500,
        "return_rate_180d": 0.35,
        "avg_discount_pct_180d": 0.50,
        "avg_rating_180d": 2.5,
        "category_diversity_180d": 1,
        "ticket_count_90d": 3,
        "negative_ticket_rate_90d": 0.8,
        "avg_resolution_hours_90d": 72,
        "days_since_signup": 500,
        "sessions_30d": 1,
        "product_views_30d": 2,
        "cart_adds_30d": 0,
        "wishlist_adds_30d": 0,
        "abandoned_carts_30d": 1,
        "email_opens_30d": 0,
        "campaign_clicks_30d": 0,
        "last_visit_days_ago": 45,
        "city_tier": "Tier 2",
        "age_group": "35-44",
        "acquisition_channel": "Paid Social",
        "loyalty_tier": "None",
        "preferred_category": "Skin Care",
        "marketing_consent": "No"
    }

    response = client.post(
        "/predict",
        json=payload
    )

    assert response.status_code == 200

    result = response.json()

    assert "churn_probability" in result
    assert "predicted_class" in result
    assert "risk_level" in result
    assert "risk_explanation" in result


def test_low_risk_customer():

    payload = {
        "recency_days": 10,
        "frequency_180d": 8,
        "monetary_180d": 6000,
        "return_rate_180d": 0.02,
        "avg_discount_pct_180d": 0.10,
        "avg_rating_180d": 4.8,
        "category_diversity_180d": 4,
        "ticket_count_90d": 0,
        "negative_ticket_rate_90d": 0,
        "avg_resolution_hours_90d": 0,
        "days_since_signup": 900,
        "sessions_30d": 15,
        "product_views_30d": 50,
        "cart_adds_30d": 12,
        "wishlist_adds_30d": 5,
        "abandoned_carts_30d": 0,
        "email_opens_30d": 10,
        "campaign_clicks_30d": 5,
        "last_visit_days_ago": 2,
        "city_tier": "Tier 1",
        "age_group": "25-34",
        "acquisition_channel": "Organic",
        "loyalty_tier": "Platinum",
        "preferred_category": "Fragrance",
        "marketing_consent": "Yes"
    }

    response = client.post(
        "/predict",
        json=payload
    )

    assert response.status_code == 200

    result = response.json()

    assert "churn_probability" in result
    assert "predicted_class" in result
    assert "risk_level" in result
    assert "risk_explanation" in result


def test_batch_predict():

    customer = {
        "recency_days": 120,
        "frequency_180d": 2,
        "monetary_180d": 1000,
        "return_rate_180d": 0.1,
        "avg_discount_pct_180d": 0.3,
        "avg_rating_180d": 4.0,
        "category_diversity_180d": 2,
        "ticket_count_90d": 1,
        "negative_ticket_rate_90d": 0.2,
        "avg_resolution_hours_90d": 20,
        "days_since_signup": 400,
        "sessions_30d": 5,
        "product_views_30d": 10,
        "cart_adds_30d": 3,
        "wishlist_adds_30d": 1,
        "abandoned_carts_30d": 2,
        "email_opens_30d": 1,
        "campaign_clicks_30d": 0,
        "last_visit_days_ago": 20,
        "city_tier": "Tier 1",
        "age_group": "25-34",
        "acquisition_channel": "Organic",
        "loyalty_tier": "Gold",
        "preferred_category": "Skin Care",
        "marketing_consent": "Yes"
    }

    response = client.post(
        "/batch_predict",
        json=[customer, customer]
    )

    assert response.status_code == 200

    results = response.json()

    assert len(results) == 2